// Create Proper AUTHENTICATION OTP Template
// Authentication templates get auto-approved by Meta!
import 'package:http/http.dart' as http;
import 'dart:convert';

const String wabaId = '576625715530014';
const String accessToken =
    'EAAeA3FDAMxkBQRzdmcnezP6hV7WVZC8OZAiUUhH9ZBYDyc0EmvN1BT4yu8QKgLBNDiIq2RN3gb1zmX28h3Hvlzd3lfiuLzeCMfAFtQbHqd1mMYlXt7WaIjtxtreSZBEvlVe6qWQspqbM1OAxAGHApTRQqTu7ri4Ney7Qo5r2OFYIgjJznfmsn3qlkZCt1DQZDZD';
const String apiVersion = 'v22.0';
const String baseUrl = 'https://graph.facebook.com';

Future<void> main() async {
  print('');
  print('╔═══════════════════════════════════════════════════════════════╗');
  print('║     🔐 Creating AUTHENTICATION OTP Template                   ║');
  print('╚═══════════════════════════════════════════════════════════════╝');
  print('');
  print('📝 AUTHENTICATION category templates are auto-approved by Meta!');
  print('   This is the correct way to send OTP codes to new users.');
  print('');

  // Try to create authentication template
  await createAuthenticationTemplate();
}

Future<void> createAuthenticationTemplate() async {
  final url = '$baseUrl/$apiVersion/$wabaId/message_templates';

  print('1️⃣ Creating OTP Authentication Template...');
  print('');

  // Authentication OTP template format per Meta's documentation
  // https://developers.facebook.com/docs/whatsapp/business-management-api/authentication-templates

  // Method 1: Try with OTP button (preferred for authentication)
  final otpButtonTemplate = {
    'name': 'aq_otp_auth',
    'category': 'AUTHENTICATION',
    'language': 'en',
    'components': [
      {
        'type': 'BODY',
        'text': 'Your verification code is {{1}}. Do not share this code.',
        'example': {
          'body_text': [
            ['123456']
          ]
        }
      },
      {
        'type': 'BUTTONS',
        'buttons': [
          {'type': 'OTP', 'otp_type': 'COPY_CODE', 'text': 'Copy Code'}
        ]
      }
    ]
  };

  print('   Attempting Method 1: OTP Button Template...');
  var result = await submitTemplate(url, otpButtonTemplate);

  if (!result) {
    // Method 2: Simple authentication template
    print('');
    print('   Attempting Method 2: Simple Authentication Template...');

    final simpleAuthTemplate = {
      'name': 'aq_verification_code',
      'category': 'AUTHENTICATION',
      'language': 'en',
      'components': [
        {
          'type': 'BODY',
          'text': '{{1}} is your verification code for AQ///bimmer.',
          'example': {
            'body_text': [
              ['123456']
            ]
          }
        }
      ]
    };

    result = await submitTemplate(url, simpleAuthTemplate);
  }

  if (!result) {
    // Method 3: Zero-click authentication
    print('');
    print('   Attempting Method 3: Zero-Click Authentication...');

    final zeroClickTemplate = {
      'name': 'aq_auth_code',
      'category': 'AUTHENTICATION',
      'language': 'en',
      'components': [
        {'type': 'BODY', 'add_security_recommendation': true},
        {'type': 'FOOTER', 'code_expiration_minutes': 5}
      ]
    };

    result = await submitTemplate(url, zeroClickTemplate);
  }

  if (!result) {
    // Method 4: UTILITY template (fallback)
    print('');
    print('   Attempting Method 4: UTILITY Template (fallback)...');

    final utilityTemplate = {
      'name': 'aq_code_delivery',
      'category': 'UTILITY',
      'language': 'en',
      'components': [
        {
          'type': 'BODY',
          'text': 'Your code: {{1}}',
          'example': {
            'body_text': [
              ['123456']
            ]
          }
        }
      ]
    };

    result = await submitTemplate(url, utilityTemplate);
  }

  print('');
  print('═══════════════════════════════════════════════════════════════');

  if (result) {
    print('✅ Template created successfully!');
    print('');
    print('📝 Next steps:');
    print(
        '   1. Wait for template approval (usually instant for AUTHENTICATION)');
    print('   2. Check template status in Meta Business Suite');
    print('   3. Update your app code to use the new template name');
  } else {
    print('❌ Could not create template automatically.');
    print('');
    print('📝 Manual creation steps:');
    print('   ─────────────────────────────────────────────');
    print(
        '   1. Go to: https://business.facebook.com/wa/manage/message-templates/');
    print('   2. Click "Create Template"');
    print('   3. Category: AUTHENTICATION');
    print('   4. Name: aq_otp_auth');
    print('   5. Language: English');
    print('   6. Select "Copy code" button option');
    print('   7. The body text will be auto-generated by Meta');
    print('   8. Submit - AUTHENTICATION templates are usually auto-approved');
  }

  print('═══════════════════════════════════════════════════════════════');
  print('');

  // Show all templates after creation
  print('📋 Current templates:');
  await listTemplates();
}

Future<bool> submitTemplate(String url, Map<String, dynamic> template) async {
  try {
    final response = await http.post(
      Uri.parse(url),
      headers: {
        'Authorization': 'Bearer $accessToken',
        'Content-Type': 'application/json',
      },
      body: json.encode(template),
    );

    final data = json.decode(response.body);

    print('   Status: ${response.statusCode}');

    if (response.statusCode == 200 || response.statusCode == 201) {
      print('   ✅ Template "${template['name']}" created!');
      print('   ID: ${data['id']}');
      print('   Status: ${data['status'] ?? 'PENDING'}');
      return true;
    } else {
      final error = data['error'];
      print('   ❌ Failed: ${error?['message'] ?? 'Unknown error'}');

      // Show more details if available
      if (error?['error_user_msg'] != null) {
        print('   Details: ${error['error_user_msg']}');
      }
      if (error?['error_subcode'] != null) {
        print('   Subcode: ${error['error_subcode']}');
      }

      return false;
    }
  } catch (e) {
    print('   ❌ Error: $e');
    return false;
  }
}

Future<void> listTemplates() async {
  try {
    final url = '$baseUrl/$apiVersion/$wabaId/message_templates?limit=100';
    final response = await http.get(
      Uri.parse(url),
      headers: {'Authorization': 'Bearer $accessToken'},
    );

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      final templates = data['data'] as List? ?? [];

      print('');
      for (var t in templates) {
        final name = t['name'];
        final status = t['status'];
        final category = t['category'];

        String icon;
        switch (status) {
          case 'APPROVED':
            icon = '✅';
            break;
          case 'PENDING':
            icon = '⏳';
            break;
          default:
            icon = '❌';
        }

        print('   $icon $name ($category) - $status');
      }
    }
  } catch (e) {
    print('   Error listing templates: $e');
  }
}
